### ISSUE TITLE
Fusion du sbet decoder et du accuracy decoder

### ISSUE THREAD

**Issue by JordanMcManus** [CIDCO-dev/SBET-decoder#18]
Il serait préférable d'avoir ces données dans le même fichier output, car ils seront utilisés dans le géoref.

C'est beaucoup plus facile et pertinent de faire le merge ici (ce qui nous économise du traitement d'interpolation dans le géoref).

Sinon, je dois ajouter un parser pour le fichier accuracy dans le géoref et faire l'interpolation...

**Comment by glabmoris** [comment]
Quelles informations de accuracy.out servent dans le georef?

**Comment by JordanMcManus** [comment]
RollSd, PitchSd, HeadingSd. Medoune en a besoin pour la calibration statique et on va en aura besoin dans LIBAC (et les autre ...AC)

**Comment by JordanMcManus** [comment]
Dans le BoresightEstimation de LISPAC, ces quantités sont hardcodés...
```
Precision << 0.03, 0.05,				// PosHorAcc, PosVerAcc 
		         0.01 * d2r, 0.01 * d2r,	// PitchRollAcc, HeadingAcc
		         0.3, 0.3,					// XLidarAcc, ZLidarAcc
		         0.05 * d2r, 0.1 * d2r,		// sigdPhiThe, sigdPsi
		         0.03, 0.05;			    // sigAxy, sigAz
```

Il serait définitivement mieux d'utiliser celles fournies par le atlans.

**Comment by MohHS** [comment]
@glabmoris @JordanMcManus  On utilise pas les incertitudes directement dans le géoréférencement. Dans le module de estimation de boresight (BoresightEstimation) ce qui est utilisé maintenant c'est un très élémentaires façons d'estimer les incertitudes des angles de visée et il nous donne meme pas les incertitudes liés au point finale! 
Nous on doit intégrer le modèle CSMU de Willian dans LisPAC pour avoir une estimation très précise des incértitudes de chaque points dans le nuage de point!
Donc, c'est bien d'avoir les incertitudes liées aux attitudes et aux positionnements qui vient dans le fichier accuracy.out!

**Comment by glabmoris** [comment]
Cet issue n'est plus pertinent puisqu'on utilise des templates APPS. On garde donc le décodeur SBET autonome.
