### ISSUE TITLE
Compilation de gui

### ISSUE THREAD

**Issue by hugoeeb** [CIDCO-dev/SBET-decoder#33]

**Comment by hugoeeb** [comment]
J'ai réussie à compiler avec QtCreator:
![Screenshot from 2019-04-08 11-18-48](https://user-images.githubusercontent.com/36771930/55736057-977bb200-59f0-11e9-8caa-780ba9ee6731.png)

Mais il manquerais l'option "Export as Text" pour que ce soit utilisable.

**Comment by glabmoris** [comment]
@HugoValcourt Regarde le code de l'éxécutable command line, tout le code nécessaire s'y trouve. Penses-tu être capable? Il faut un appel à QFileDialog pour obtenir le nom du fichier, et ensuite parser le fichier

**Comment by hugoeeb** [comment]
Oui, je devrais être en mesure de faire ça.

**Comment by hugoeeb** [comment]
Pull Request #36
